## Weekly Customer Cohort Retention Analysis

In [2]:
# import pytho modules for analysis
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as dt

In [4]:
# Specify the column(s) to be parsed as dates
parse_dates = ['InvoiceDate']

# Specify the column(s) and their desired data types
dtype_dict = {
    'CustomerID': str
}

# Path to the dataset
dataset_path = "../dataset1-online-retail-enhanced.csv"

# Read the CSV file, parsing the specified columns as datetime and setting data types for others
dataset1 = pd.read_csv(dataset_path, encoding='unicode_escape', parse_dates=parse_dates, dtype=dtype_dict)

# print shape of the data
print(f"Enhaced dataset shape: {dataset1.shape}")

# Display the first few rows of the dataset
dataset1.head()

Enhaced dataset shape: (397924, 12)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDateTime,UnitPrice,CustomerID,Country,InvoiceDate,InvoiceAmount,InvoiceDayOfWeek,InvoiceYearMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,2010-12-01,15.30,Wednesday,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010-12-01,20.34,Wednesday,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,2010-12-01,22.00,Wednesday,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010-12-01,20.34,Wednesday,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010-12-01,20.34,Wednesday,2010-12

In [5]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397924 entries, 0 to 397923
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   InvoiceNo         397924 non-null  int64
 1   StockCode         397924 non-null  object
 2   Description       397924 non-null  object
 3   Quantity          397924 non-null  int64
 4   InvoiceDateTime   397924 non-null  object
 5   UnitPrice         397924 non-null  float64
 6   CustomerID        397924 non-null  object
 7   Country           397924 non-null  object
 8   InvoiceDate       397924 non-null  datetime64[ns]
 9   InvoiceAmount     397924 non-null  float64
 10  InvoiceDayOfWeek  397924 non-null  object
 11  InvoiceYearMonth  397924 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(7)
memory usage: 36.4+ MB